
@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.acess_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Jonny Doe Jr",
  "documentId": "090.090.090-02",
  "password": "123456"
}

###
# @name get_one_account
GET {{baseUrl}}/accounts/3f9672a1-0627-4eaa-bdf7-6750a2ec6296
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name list_accounts
GET {{baseUrl}}/accounts
Content-Type: application/json
Authorization: Bearer {{authToken}}
###

# @name update_account
PATCH {{baseUrl}}/accounts/d57eafb2-979f-4c77-ad45-c9d4ccf5d41c
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Bruce Wayne Jr",
  "documentId": "777.888.977-01"
}
###

# @name delete_account
DELETE {{baseUrl}}/accounts/3f9672a1-0627-4eaa-bdf7-6750a2ec6296
Content-Type: application/json
Authorization: Bearer {{authToken}}
###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "documentId": "123.123.123-12",
  "password": "123456"
}
###

# @name list_recipients
GET {{baseUrl}}/recipients
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name recipient
POST {{baseUrl}}/recipients
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"name": "Marcus Fenix",
	"documentId": "555.666.777-88",
	"address": "1047 Brea, CA 92821",
	"phone": "(714) 438-7243",
	"email": "marcusfenix@email.com"
}
