
@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.acess_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Jonny Doe Jr",
  "documentId": "090.090.090-02",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "docuemntId": "090.090.090-02",
  "password": "123456"
}